apiVersion: v1
kind: Service
metadata:
  name: proxy-node-gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6100
    targetPort: 80
  - name: "6601"
    port: 6601
    targetPort: 6601
  selector:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
